### ISSUE TITLE
CubicTicTacToe random_player() returns the second player over and over after the second call

### ISSUE THREAD

**Issue by acneumyer** [jyang00/CMSC421Team1#1]
![image](https://user-images.githubusercontent.com/65512635/140410652-95351ca3-02b3-4609-a519-f4207811727a.png)

**Comment by acneumyer** [comment]
Also, display_stats() uses game.x_score, etc., when it should be self.x_score, etc.

**Comment by tbrinkle** [comment]
Sorry, late reply. random_player works as intended. The idea is that it chooses the first player randomly amongst the two, but any subsequent calls returns the second player. This is the alternative method to choose from versus the others that set X as the first player and O as the second. (I suppose renaming the method or returning null after the first two calls would help make sense).
display_stats() typo appears to be fixed.

Thanks
